// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPuFGmoSbIMd5Gp4n2ZR2yGDwoEU8XsRk',
    appId: '1:485487413795:web:4b5fe970f47b72990f3f96',
    messagingSenderId: '485487413795',
    projectId: 'review-foods',
    authDomain: 'review-foods.firebaseapp.com',
    storageBucket: 'review-foods.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf7cd6_tE5tWZjAjMI5f4c--ghExhgKTU',
    appId: '1:485487413795:android:889379dcd9e7ab540f3f96',
    messagingSenderId: '485487413795',
    projectId: 'review-foods',
    storageBucket: 'review-foods.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6fRhNj11_XrBYuJhxM-wCRZDFbXqoGHA',
    appId: '1:485487413795:ios:86130f1433381c950f3f96',
    messagingSenderId: '485487413795',
    projectId: 'review-foods',
    storageBucket: 'review-foods.appspot.com',
    iosClientId: '485487413795-njprjj04a1uvi7p5err121kav302uk03.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudServiceFoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6fRhNj11_XrBYuJhxM-wCRZDFbXqoGHA',
    appId: '1:485487413795:ios:27424194a79b21ac0f3f96',
    messagingSenderId: '485487413795',
    projectId: 'review-foods',
    storageBucket: 'review-foods.appspot.com',
    iosClientId: '485487413795-5mhfn5rus02etrn5ttg9pr36b983rmd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudServiceFoods.RunnerTests',
  );
}
